### ISSUE TITLE
Change the wallpaper based on the night light settings

### ISSUE THREAD

**Issue by rodvb25** [dusansimic/dynamic-wallpaper#63] opened 2022-11-19 23:31 UTC
This is useful for people who use dark mode all the time, but want the wallpaper to be darker at night. 

If night light is off, wallpaper will be light mode and vice versa.

I don't know if this is out of scope but I think it will add to the software.

**Comment by dusansimic** [comment] 2022-11-22 10:13
This app was designed with the idea of making a Dynamic Wallpaper that reacts to light/dark theme and it's meant to do only that so it would stay minimal. What you suggest however would be very useful to have as a feature and is already available with [Dynamic Wallpaper Editor](https://beta.flathub.org/apps/details/com.github.maoschanz.DynamicWallpaperEditor) (I know, names are very similar and it might be confusing 😅).

A combination of those features would be fantastic (having an automatic mode switcher for time of day) and with that, the wallpaper would get switched automatically (this would be integrated into GNOME). I believe there are feature requests for that already but I can't find them at the moment.

I'll close this issue since I don't plan on implementing such feature (it already exists in another app).

**Closed by dusansimic** 2022-11-22 10:13 UTC
